apiVersion: v1
kind: ConfigMap
metadata:
  name: robinhood-config
  namespace: robinhood-clone
  labels:
    app: robinhood-clone
data:
  # Database configuration
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "robinhood_clone"
  
  # Redis configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Flask configuration
  FLASK_ENV: "production"
  FLASK_DEBUG: "false"
  
  # Alpha Vantage API configuration
  ALPHA_VANTAGE_BASE_URL: "https://www.alphavantage.co/query"
  
  # Application settings
  API_RATE_LIMIT: "5"
  API_RATE_LIMIT_PERIOD: "60"
  CACHE_DEFAULT_TIMEOUT: "300"
  
  # Frontend configuration
  REACT_APP_API_URL: "http://backend-service:5001/api"
  
  # Logging configuration
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: Secret
metadata:
  name: robinhood-secrets
  namespace: robinhood-clone
  labels:
    app: robinhood-clone
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  # To encode: echo -n 'your-secret' | base64
  DATABASE_USER: cG9zdGdyZXM=  # postgres
  DATABASE_PASSWORD: cGFzc3dvcmQ=  # password
  SECRET_KEY: eW91ci1zZWNyZXQta2V5LWhlcmU=  # your-secret-key-here
  JWT_SECRET_KEY: and0LXNlY3JldC1rZXktaGVyZQ==  # jwt-secret-key-here
  ALPHA_VANTAGE_API_KEY: ZGVtbw==  # demo (replace with real API key)