apiVersion: v1
kind: Namespace
metadata:
  name: robinhood-clone
  labels:
    name: robinhood-clone
    app: stock-trading-app
---
# Resource quota to limit resource usage
apiVersion: v1
kind: ResourceQuota
metadata:
  name: robinhood-quota
  namespace: robinhood-clone
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "4"
    pods: "20"
    services: "10"
---
# Limit range to set default resource limits
apiVersion: v1
kind: LimitRange
metadata:
  name: robinhood-limits
  namespace: robinhood-clone
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container